In [1]:
import numpy as np
import sys

In [2]:
## initializing an array
a= np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [4]:
b = np.array([[5.0,6.0],[6.9,6]])

In [5]:
b

array([[5. , 6. ],
       [6.9, 6. ]])

In [6]:
print(b)

[[5.  6. ]
 [6.9 6. ]]


In [7]:
#Get dimensions
a.ndim

1

In [8]:
b.ndim

2

In [11]:
#shape
a.shape

(3,)

In [10]:
b.shape

(2, 2)

In [12]:
#Get type
a.dtype

dtype('int32')

In [13]:
type(a)

numpy.ndarray

In [17]:
#get size
a.itemsize

4

In [15]:
c= np.array([1,2,3], dtype='int16')

In [16]:
c.dtype

dtype('int16')

In [18]:
#get size
c.itemsize

2

In [19]:
a.size

3

In [20]:
a.size * a.itemsize

12

In [22]:
a.nbytes

12

### accessing/changing rows, elements,etc 

In [24]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [25]:
a.shape

(2, 7)

In [26]:
#getting specific position
a[1,5]

13

In [27]:
a[1,-2]

13

In [29]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
a[:,0]

array([1, 8])

In [33]:
### startIndix+endIndex+stepsize
a[0,:7:2]

array([1, 3, 5, 7])

In [35]:
a[0,0:-1:1]

array([1, 2, 3, 4, 5, 6])

In [37]:
##changing columns 
a[:,2] 

array([ 3, 10])

In [45]:
a[:,2] = 10

In [46]:
print(a)

[[ 1  2 10  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


### Initializing different types of arrays

In [54]:
## All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
# All 1s matrix
np.ones((2,3), dtype='int16')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [59]:
#all values with specific number
np.full((2,2),99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [60]:
b

array([[5. , 6. ],
       [6.9, 6. ]])

In [62]:
np.full_like(b,4)

array([[4., 4.],
       [4., 4.]])

In [65]:
a

array([[ 1,  2, 10,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [66]:
#random decimals no
np.random.rand(4,2)

array([[0.20090343, 0.81421751],
       [0.08738802, 0.40752945],
       [0.49242939, 0.51175109],
       [0.32880683, 0.21759422]])

In [67]:
a

array([[ 1,  2, 10,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [71]:
np.random.random_sample(a.shape)

array([[0.05149575, 0.56745835, 0.81336588, 0.99775435, 0.24563202,
        0.73435778, 0.71353347],
       [0.47116514, 0.35241288, 0.60173132, 0.69278705, 0.25758368,
        0.78744266, 0.9127235 ]])

In [80]:
#random int values
np.random.randint(2,14,size=(3,3))

array([[ 7, 13,  8],
       [12,  2, 10],
       [12, 11, 12]])

In [83]:
## identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [85]:
arr = np.array([[1,2,3]])
r = np.repeat(arr,3, axis=0)

In [86]:
r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [92]:
r = np.repeat(arr,5, axis=1)

In [93]:
r

array([[1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]])

In [102]:
out = np.ones((5,5))
print(out)
out2 = np.zeros((3,3))
out2[1,1]=9
print(out2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [103]:
out[1:4,1:4]=out2

In [104]:
out

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### be careful with copying arrays 

In [105]:
a=np.array([1,2,3])
b=a                   #### this actually doesn't just copy it also acts as reference... therefore chaning b, chnages a
b[0]=100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [107]:
### instead do this
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)
print(a)   #### ta da

[100   2   3]
[1 2 3]


### basic mathematics 

In [108]:
a= np.array([2,3,4,5])
a

array([2, 3, 4, 5])

In [109]:
a+2

array([4, 5, 6, 7])

In [110]:
a/2

array([1. , 1.5, 2. , 2.5])

In [112]:
np.sin(a)

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [113]:
np.cos(a)

array([-0.41614684, -0.9899925 , -0.65364362,  0.28366219])

### Linear Algebra 

In [124]:
a = np.ones((3,2))
print(a)
b=np.full((2,3),2)
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[2 2 2]
 [2 2 2]]


In [126]:
np.matmul(a,b)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

### statistics 

In [127]:
out = np.array([[1,2,3],[4,5,6]])

In [128]:
out

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
np.min(out)

1

In [130]:
np.max(out)

6

### reorganizing arrays

In [131]:
before = np.array([[1,2,3,4],[5,6,7,8]])

In [132]:
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [141]:
after = before.reshape((8,1)) ## works as much the size remains same
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [146]:
### Vertically stacking arrays
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [148]:
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [152]:
np.vstack([v1,v1,v2,v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [153]:
#horizontal stack
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])
np.hstack((h1,h2))

array([1, 2, 3, 4, 5, 6, 7, 8])

### miscellanious

In [158]:
#### loading the data from file

In [154]:
data = np.genfromtxt("data.txt", delimiter=',')

In [155]:
data

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,   2.,   3.,
          5.,   8.,   4., 235.],
       [  6.,   5.,   4.,   3.,   5.,   7.,   4.,   7.,   2.,   3.,   6.,
          3.,   8.,   8., 346.],
       [  2.,   3.,   7.,   9.,   4.,   5.,   9.,   3.,   1.,   6.,  99.,
          3.,   2.,   7.,  66.]])

In [157]:
data.astype("int32") ### converting to type int

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,   2,   3,   5,   8,
          4, 235],
       [  6,   5,   4,   3,   5,   7,   4,   7,   2,   3,   6,   3,   8,
          8, 346],
       [  2,   3,   7,   9,   4,   5,   9,   3,   1,   6,  99,   3,   2,
          7,  66]])

### Boolean masking and advance indexing

In [162]:
data>50

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False,  True]])

In [171]:
data[data>50]

array([235., 346.,  99.,  66.])

In [165]:
np.any(data>50, axis=0)

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False,  True])

In [173]:
((data>50)&(data<100))

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False,  True]])

In [180]:
a = np.random.rand(6,5)

In [181]:
a

array([[0.75635042, 0.26034943, 0.36471559, 0.12999399, 0.02258852],
       [0.09383624, 0.2847714 , 0.76044282, 0.98862603, 0.76815946],
       [0.67512314, 0.26298053, 0.22830887, 0.36132644, 0.50588043],
       [0.01136276, 0.41824073, 0.46854097, 0.5257196 , 0.98482257],
       [0.68079013, 0.17626488, 0.48343966, 0.32665182, 0.92600418],
       [0.70078748, 0.09532193, 0.06217695, 0.38895719, 0.97386386]])

In [182]:
a[2:4,0:2]

array([[0.67512314, 0.26298053],
       [0.01136276, 0.41824073]])

In [186]:
a[[0,1,2,3],[1,2,3,4]]

array([0.26034943, 0.76044282, 0.36132644, 0.98482257])

In [193]:
a[[0,4,5],3:]

array([[0.12999399, 0.02258852],
       [0.32665182, 0.92600418],
       [0.38895719, 0.97386386]])

### more practice 

In [194]:
a

array([[0.75635042, 0.26034943, 0.36471559, 0.12999399, 0.02258852],
       [0.09383624, 0.2847714 , 0.76044282, 0.98862603, 0.76815946],
       [0.67512314, 0.26298053, 0.22830887, 0.36132644, 0.50588043],
       [0.01136276, 0.41824073, 0.46854097, 0.5257196 , 0.98482257],
       [0.68079013, 0.17626488, 0.48343966, 0.32665182, 0.92600418],
       [0.70078748, 0.09532193, 0.06217695, 0.38895719, 0.97386386]])

In [200]:
arr = np.random.randint(1,9,(5,5))

In [201]:
arr

array([[3, 3, 6, 4, 2],
       [2, 5, 5, 8, 8],
       [7, 7, 8, 3, 7],
       [1, 4, 4, 3, 7],
       [5, 2, 6, 6, 2]])

In [202]:
#Adding all the rows
[sum(i) for i in arr]

[18, 28, 32, 19, 21]

In [203]:
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.flags)
print(arr.strides)

25
(5, 5)
2
int32
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

(20, 4)


### Transpose 

In [212]:
arr2 = np.array([[1,2,3,4,5,6,7,8],[2,5,7,8,0,7,5,4]])

In [213]:
arr2

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [2, 5, 7, 8, 0, 7, 5, 4]])

In [214]:
arr2.strides

(32, 4)

In [210]:
arr2.T

array([[1, 2],
       [2, 5],
       [3, 7],
       [4, 8],
       [5, 0],
       [6, 7],
       [7, 5],
       [8, 4]])

In [215]:
arr2.T.strides

(4, 32)

### axis value

In [217]:
arr2

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [2, 5, 7, 8, 0, 7, 5, 4]])

In [222]:
np.sum(arr2, axis=0) # column wise addition(when axis=0)

array([ 3,  7, 10, 12,  5, 13, 12, 12])

In [223]:
np.sum(arr2, axis=1) #row wise addition(when axis=1)

array([36, 38])

In [228]:
arr = np.random.randint(1,50, (10,4))

In [229]:
arr

array([[17,  9, 33, 11],
       [48, 30, 23, 12],
       [21, 45, 20, 35],
       [ 4,  3, 38, 21],
       [39, 19, 24, 43],
       [ 4, 16, 45, 43],
       [45, 43,  9, 46],
       [26, 41, 44, 29],
       [37,  6,  3, 13],
       [23, 21, 48, 18]])

In [234]:
np.argsort(arr, axis=1)

array([[1, 3, 0, 2],
       [3, 2, 1, 0],
       [2, 0, 3, 1],
       [1, 0, 3, 2],
       [1, 2, 0, 3],
       [0, 1, 3, 2],
       [2, 1, 0, 3],
       [0, 3, 1, 2],
       [2, 1, 3, 0],
       [3, 1, 0, 2]], dtype=int64)

### BroadCasting 

In [243]:
data = np.random.rand(50).reshape(10,5)

In [244]:
data

array([[0.82865795, 0.229252  , 0.54035446, 0.41189817, 0.71893409],
       [0.65105013, 0.77343629, 0.97987189, 0.71718451, 0.98933868],
       [0.55832462, 0.06130278, 0.85569639, 0.76411199, 0.76876321],
       [0.45381475, 0.89932743, 0.32267858, 0.87480023, 0.76958679],
       [0.05290689, 0.67013565, 0.34140448, 0.94433683, 0.60685941],
       [0.45728145, 0.78452214, 0.84318138, 0.54696249, 0.05801316],
       [0.72865599, 0.84018302, 0.45076123, 0.97099184, 0.08949316],
       [0.84564867, 0.88884155, 0.0053269 , 0.13256012, 0.94755013],
       [0.23330301, 0.57029899, 0.13813335, 0.20989921, 0.21603085],
       [0.98746068, 0.97343434, 0.25459582, 0.16926433, 0.12571041]])

In [245]:
data+5

array([[5.82865795, 5.229252  , 5.54035446, 5.41189817, 5.71893409],
       [5.65105013, 5.77343629, 5.97987189, 5.71718451, 5.98933868],
       [5.55832462, 5.06130278, 5.85569639, 5.76411199, 5.76876321],
       [5.45381475, 5.89932743, 5.32267858, 5.87480023, 5.76958679],
       [5.05290689, 5.67013565, 5.34140448, 5.94433683, 5.60685941],
       [5.45728145, 5.78452214, 5.84318138, 5.54696249, 5.05801316],
       [5.72865599, 5.84018302, 5.45076123, 5.97099184, 5.08949316],
       [5.84564867, 5.88884155, 5.0053269 , 5.13256012, 5.94755013],
       [5.23330301, 5.57029899, 5.13813335, 5.20989921, 5.21603085],
       [5.98746068, 5.97343434, 5.25459582, 5.16926433, 5.12571041]])

In [247]:
data+np.array([1,2,3,4,5]) ### worked as number of columns are same

array([[1.82865795, 2.229252  , 3.54035446, 4.41189817, 5.71893409],
       [1.65105013, 2.77343629, 3.97987189, 4.71718451, 5.98933868],
       [1.55832462, 2.06130278, 3.85569639, 4.76411199, 5.76876321],
       [1.45381475, 2.89932743, 3.32267858, 4.87480023, 5.76958679],
       [1.05290689, 2.67013565, 3.34140448, 4.94433683, 5.60685941],
       [1.45728145, 2.78452214, 3.84318138, 4.54696249, 5.05801316],
       [1.72865599, 2.84018302, 3.45076123, 4.97099184, 5.08949316],
       [1.84564867, 2.88884155, 3.0053269 , 4.13256012, 5.94755013],
       [1.23330301, 2.57029899, 3.13813335, 4.20989921, 5.21603085],
       [1.98746068, 2.97343434, 3.25459582, 4.16926433, 5.12571041]])

In [249]:
data+np.array([1,2,3,4]) # won't work as number of columns are different

ValueError: operands could not be broadcast together with shapes (10,5) (4,) 

In [253]:
arr = data+np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[1]])

In [254]:
arr.shape

(10, 5)

### Handy functions 

In [257]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [264]:
arr =np.linspace(1,10,30)

In [265]:
arr

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [266]:
## calculating exponential values
np.exp(arr)

array([2.71828183e+00, 3.70745192e+00, 5.05657641e+00, 6.89664101e+00,
       9.40629655e+00, 1.28292040e+01, 1.74976916e+01, 2.38650201e+01,
       3.25493898e+01, 4.43939611e+01, 6.05487167e+01, 8.25821127e+01,
       1.12633359e+02, 1.53620113e+02, 2.09521757e+02, 2.85765748e+02,
       3.89754573e+02, 5.31584447e+02, 7.25025551e+02, 9.88858971e+02,
       1.34870014e+03, 1.83948584e+03, 2.50886617e+03, 3.42183089e+03,
       4.66701921e+03, 6.36532576e+03, 8.68163815e+03, 1.18408458e+04,
       1.61496745e+04, 2.20264658e+04])

In [274]:
arr2 = np.arange(12)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [275]:
arr2.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [278]:
np.sqrt(arr2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [280]:
def arrfunc(x,y):
    return x+y
userDefinedFunction = np.fromfunction(arrfunc,(5,10),dtype=int)

In [281]:
userDefinedFunction

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])